
services:
  - type: web
    name: terra-xmd
    env: node
    plan: free
    repo: https://github.com/PRINCE-PREMIUM-MDX/PRINCE-MD.git
    branch: main
    buildCommand: npm install
    startCommand: node index.js
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: MODE
        value: public
      - key: PREFIX
        value: .
      - key: BOT_NAME
        value: PRINCE-MD
      - key: OWNER_NUMBER
        value: +243860885022
